
#!/bin/bash

#PBS -l walltime=96:00:00,select=1:ncpus=20:mem=8gb
#PBS -J 2-31:1
#PBS -A st-tdjc-1
#PBS -N onedim-concrete
#PBS -m abe
#PBS -M gian.diluvi@stat.ubc.ca
#PBS -o /scratch/st-tdjc-1/madmix/toy_examples/onedim/output/concrete_^array_index^.txt
#PBS -e /scratch/st-tdjc-1/madmix/toy_examples/onedim/errors/concrete_^array_index^.txt
################################################################################

module load python/3.7.3
module load py-argparse/1.4.0-py3.7.3
module load py-pip/19.0.3-py3.7.3

cd $PBS_O_WORKDIR

export PYTHONPATH=.


params=`sed "${PBS_ARRAY_INDEX}q;d" settings.config`  # read the settings file in current iteration
param_array=( $params )                               # save current row of settins in param_array

# run code
python ../tests.py -d 1 --target 'cauchy' -B 1000 --reps ${param_array[0]} --tol 0.0 --stop 'default' --kl --lbvi_smc -N 50 --smc 'smc' --maxiter 30 --smc_eps 0.05 --smc_sd 1 --smc_T 100 --smc_w_maxiter 10 --smc_b_maxiter 10 --smc_cacheing --outpath '/scratch/st-tdjc-1/lbvi/cauchy/' --verbose
