
#!/bin/bash

#PBS -l walltime=96:00:00,select=1:ncpus=32:mem=64gb
#PBS -J 2-31:1
#PBS -A st-tdjc-1
#PBS -N onedim-concrete
#PBS -m abe
#PBS -M gian.diluvi@stat.ubc.ca
#PBS -o /scratch/st-tdjc-1/madmix/toy_examples/onedim/output/concrete_^array_index^.txt
#PBS -e /scratch/st-tdjc-1/madmix/toy_examples/onedim/errors/concrete_^array_index^.txt
################################################################################

module load python/3.8.10
module load py-argparse/1.4.0-py3.8.10
module load py-pip/21.1.2-py3.8.10

cd $PBS_O_WORKDIR

export PYTHONPATH=.


params=`sed "${PBS_ARRAY_INDEX}q;d" onedim_settings.txt`  # read the settings file in current iteration
param_array=( $params )                            # save current row of settins in param_array

# run code
python ../run_concrete.py --target 'onedim' --temp ${param_array[1]} --depth ${param_array[2]} --width ${param_array[3]} --lr ${param_array[4]} --maxiters 10000 --idx ${param_array[0]} --outpath '/scratch/st-tdjc-1/madmix/toy_examples/onedim/'
